# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53f7088f6744c26660ab621a80032b2c1c0b245f78c554c9e376c4e3d69544dd8ecbc9d1d4dbf2dee9a9998d400dc86cef821b3202d559bacc17fc41130409ac

test:
  secret_key_base: 67cccb63ee15fa6a23e6e6cb323ef6aac1156369903d16ea83213ca1ea9a5ceeac02793e820abfd7d3b7c7c024c8aa3bbc358bfdc429c66986420bb133d4282f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
